# Generated by Django 4.2.11 on 2024-05-18 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
