# Generated by Django 4.2.11 on 2024-05-18 11:55
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240518_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
