# Generated by Django 4.2.11 on 2024-05-09 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_auto_20240509_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='apptype',
            options={'ordering': ['name']},
        ),
    ]
